### ISSUE TITLE
New MQTT Topics

### ISSUE THREAD

**Issue by theskyisthelimit** [spitzlbergerj/MMM-TeslaLogger#11]
Hi Josef,
I hope you are doing well!

Teslamate just released an interesting update with 3 new MQTT topics.
Maybe it would be interesting to add them to the Module?

```
teslamate/cars/1/frunk_open <- true/false
teslamate/cars/1/trunk_open<- true/false
teslamate/cars/1/elevation <- string
```

**Comment by spitzlbergerj** [comment]
Hi,
before I can display more data in the module, I have to rebuild the whole module so that you can change the order in the list display as you like. Unfortunately this is a big change, because I never intended this. I don't know when I can start this modification. Unfortunately, it is also the case that I do not use the list display ...
